version: '3'
services:
  notification-server:
    build: .
    image: notifier
    container_name: notification-server
    restart: unless-stopped
    environment:
      - DB=
    ports:
      - "5000:5000"
    volumes:
      - .:/app